[fix]: Fixed padding issue in notifications
delta/dalal-street-client pull request #141
Opened 2022-03-15 14:49 UTC by satyamurti

2022-03-15 15:20 UTC, Sudhindra3000 approved these changes

2022-03-16 05:25 UTC, dhruv1294 requested changes
there is yours 6th sem hostel fees pdf bro lol remove that

2022-03-16 12:27 UTC, kelpikz approved these changes

2022-03-16 12:33 UTC, dhruv1294 approved these changes

2022-03-16 12:34 UTC, merged