[WIP]: Trading dashboard
delta/dalal-street-client pull request #24
Opened 2021-12-03 10:51 UTC by satyamurti

2021-12-18 13:41 UTC, Sudhindra3000 requested changes

2021-12-18 13:41 UTC, Sudhindra3000 commented on lib/blocs/user/user_state.dart
> +class SubscriptionDataLoaded extends UserState {
`UserBloc` is only meant for User authentication state. How about we shift this logic to a separate `SubscriptionBloc`?

2021-12-18 13:41 UTC, Sudhindra3000 commented on lib/blocs/user/user_state.dart
> +class SubscriptionDataLoaded extends UserState {
And `SubscriptionBloc` should be only accesible to the Home Pages. We need to see how to implement that

2021-12-18 14:48 UTC, Sudhindra3000 commented on lib/blocs/user/user_state.dart
> +class SubscriptionDataLoaded extends UserState {
Or we could even have all the subscription ids in User data itself. In splash page when we are getting user data from stored session id, we can make all the common subscription calls, and store the ids in `UserDataLoaded` state

2021-12-19 04:45 UTC, siva2204 commented on lib/blocs/user/user_state.dart
> +class SubscriptionDataLoaded extends UserState {
And we have  to call `unSubscribe` with the subscription I'd, once we're closing with stream.

2021-12-20 07:39 UTC, dhruv1294 approved these changes

2021-12-20 09:57 UTC, dhruv1294 commented
btw is resposive a typo??

2021-12-20 14:17 UTC, satyamurti commented
> btw is resposive a typo??

Yes sorry my bad

2021-12-20 18:23 UTC, Sudhindra3000 commented on lib/pages/home_page.dart
> +    BlocProvider.of<CompaniesBloc>(context).add(const GetStockList());
use `context.read()` here too instead of `BlocProvider.of()` ?

2021-12-20 18:23 UTC, Sudhindra3000 commented on lib/pages/home_page.dart
> +  SubscriptionId? _stockPricesSubscriptionId;
Remove this field from the Widget and integrate in the Bloc itself?

2021-12-20 18:26 UTC, satyamurti commented on lib/pages/home_page.dart
> +  SubscriptionId? _stockPricesSubscriptionId;
but for unsubscribing we need to pass this id and we call this in dispose function of widget

2021-12-20 18:35 UTC, Sudhindra3000 commented on lib/pages/home_page.dart
> +  SubscriptionId? _stockPricesSubscriptionId;
The subId is there in `SubscriptionDataLoaded` state right. In dispose function we can get current state of subBloc with subBloc.state, cast it to `SubscriptionDataLoaded`to get the subId.

2021-12-20 20:31 UTC, satyamurti commented on lib/pages/home_page.dart
> +  SubscriptionId? _stockPricesSubscriptionId;
Okay I did that

2021-12-20 20:31 UTC, satyamurti commented on lib/pages/home_page.dart
> +    BlocProvider.of<CompaniesBloc>(context).add(const GetStockList());
Okay

2021-12-21 04:53 UTC, Sudhindra3000 commented on lib/pages/home_page.dart
> +      context.read<SubscribeCubit>().unsubscribe(_stockPricesSubscriptionId);
remove the local field `SubscriptionId? _stockPricesSubscriptionId` and just do `context.read<SubscribeCubit>().unsubscribe()`. We can do the casting `state is SubscriptionDataLoaded` directly inside the unsubscribe function

2021-12-21 04:53 UTC, Sudhindra3000 commented on lib/pages/home_page.dart
> +                        ),
The widget tree is pretty big. Split it into sub parts with meaningful names. Refer `LoginPage` and `RegisterPage` once

2021-12-21 18:28 UTC, Sudhindra3000 approved these changes

2021-12-21 18:58 UTC, merged