[WIP] Daily challenges
delta/dalal-street-client pull request #27
Opened 2021-12-22 15:06 UTC by Sudhindra3000

2021-12-24 14:22 UTC, satyamurti requested changes

2021-12-24 14:22 UTC, satyamurti commented on lib/blocs/auth/login/login_cubit.dart
> +      final stockResponse = await actionClient.getStockList(
I don't think calling these many rpc calls in login cubit is good. Login Cubit should be responsible for only Logging in the User.

2021-12-24 14:22 UTC, satyamurti commented on lib/blocs/auth/login/login_cubit.dart
> +        options: sessionOptions(sessionId),
How about we have a separate cubits for these are update loading bar and text showing what is current state of the app in UI according to the calls , similar to popular games like league of legends , PUBG , Valorant.

2021-12-24 14:22 UTC, satyamurti commented on lib/blocs/auth/login/login_cubit.dart
> +        options: sessionOptions(sessionId),
![image](https://user-images.githubusercontent.com/59143264/147358519-8be2f4e5-153e-4d6d-8dc8-01e24c80a388.png)
![image](https://user-images.githubusercontent.com/59143264/147358542-4c46cd03-6c3e-4cf9-aa16-e3eaa069e4e8.png)
![image](https://user-images.githubusercontent.com/59143264/147358566-164108d2-98e2-4c2d-af1c-94880f397da0.png)
![image](https://user-images.githubusercontent.com/59143264/147358581-9b768293-e478-4682-92b3-9702d41763c2.png)

2021-12-24 14:22 UTC, satyamurti commented on lib/blocs/auth/login/login_cubit.dart
> +        options: sessionOptions(sessionId),
Like this we can show in UI

2021-12-24 14:22 UTC, satyamurti commented on lib/blocs/daily_challenges/daily_challenges_page_cubit.dart
> +  Future<void> listenToGameStateSteam() async {
Steam is typo?

2021-12-24 14:23 UTC, satyamurti commented on lib/blocs/auth/login/login_cubit.dart
> +        options: sessionOptions(sessionId),
This is League of Legends

2021-12-24 14:49 UTC, Sudhindra3000 commented on lib/blocs/daily_challenges/daily_challenges_page_cubit.dart
> +  Future<void> listenToGameStateSteam() async {
ya i will change

2021-12-24 14:55 UTC, satyamurti approved these changes

2021-12-24 14:56 UTC, Sudhindra3000 commented on lib/blocs/auth/login/login_cubit.dart
> +        options: sessionOptions(sessionId),
Nice idea. but it wont look as appealing in our case because all the calls are completed pretty fast

2021-12-24 14:56 UTC, Sudhindra3000 commented on lib/blocs/auth/login/login_cubit.dart
> +        options: sessionOptions(sessionId),
Atleast that is the case now. If we add more streams and other stuff then it might take some time

2021-12-24 15:12 UTC, satyamurti commented on lib/blocs/auth/login/login_cubit.dart
> +        options: sessionOptions(sessionId),
okay fine

2021-12-25 03:37 UTC, satyamurti requested changes

2021-12-25 03:37 UTC, satyamurti commented on lib/pages/daily_challenges/daily_challenges_page.dart
> +    return Column(
Use `Responsive` widget here. Refer to homepage.

2021-12-25 10:16 UTC, Sudhindra3000 commented on lib/pages/daily_challenges/daily_challenges_page.dart
> +    return Column(
Ok

2021-12-25 10:19 UTC, Sudhindra3000 commented on lib/pages/daily_challenges/daily_challenges_page.dart
> +    return Column(
Actually i'm doing a separate pr for UI. I will do this there

2021-12-25 13:50 UTC, satyamurti approved these changes

2021-12-25 13:58 UTC, merged