[WIP]: Add Exchange Page
delta/dalal-street-client pull request #29
Opened 2021-12-23 18:27 UTC by dhruv1294

2021-12-27 05:37 UTC, Sudhindra3000 commented on lib/pages/exchange_page.dart
> +  Container _stockExchangeItem(
Make this as a separate widget

2021-12-28 15:55 UTC, Sudhindra3000 approved these changes

2021-12-28 16:24 UTC, satyamurti requested changes

2021-12-28 16:24 UTC, satyamurti commented on lib/blocs/exchange/exchange_cubit.dart
> +    final exchangeStream = getIt<GlobalStreams>().stockExchangeStream;
So this stream will start at the start of app?

2021-12-28 16:27 UTC, dhruv1294 commented on lib/blocs/exchange/exchange_cubit.dart
> +    final exchangeStream = getIt<GlobalStreams>().stockExchangeStream;
yes ig since its been made a global stream

2021-12-28 16:28 UTC, dhruv1294 commented on lib/blocs/exchange/exchange_cubit.dart
> +    final exchangeStream = getIt<GlobalStreams>().stockExchangeStream;
coz the stocklist map will need to be updated from this stream as well

2021-12-28 16:35 UTC, satyamurti approved these changes

2021-12-28 16:39 UTC, merged