[WIP]: Company Page
delta/dalal-street-client pull request #34
Opened 2021-12-25 19:00 UTC by satyamurti

2021-12-29 06:55 UTC, satyamurti commented
@simmiggrwl  
1. Break Company page into small widgets and place them in `lib/pages/homepage/components/` directory
2. Pull rebase from main branch properly
3. Add proper comments wherever neccessary

2022-01-04 17:39 UTC, satyamurti reviewed
There are some conflicts with master branch please pull rebase and resolve them

2022-01-04 17:39 UTC, satyamurti commented on lib/pages/homepage/components/choose_buy_or_sell_bottom_sheet.dart
> +import 'package:dalal_street_client/pages/homepage/components/trading_bottom_sheet.dart';
Rename homepage directory to company and place `company_page.dart` there.

 
import 'package:dalal_street_client/pages/`company`/components/trading_bottom_sheet.dart';

2022-01-06 04:55 UTC, dhruv1294 commented on lib/blocs/stock_prices/stock_prices_bloc.dart
> +class StockPricesBloc extends Bloc<StockPricesEvent, StockPricesState> {
Should we change this bloc to cubit similar to exchangeStreamCubit or its fine..?

2022-01-06 04:55 UTC, dhruv1294 commented on lib/pages/company_page/components/trading_bottom_sheet.dart
> +                Navigator.pop(context);
if we just show the snackbar and let them try again instead of navigator.pop()

2022-01-06 04:55 UTC, dhruv1294 commented on lib/pages/company_page/components/trading_bottom_sheet.dart
> +                                    child: SvgPicture.asset(
Are these SVG assets loading for u in mobile?

2022-01-06 09:36 UTC, Sudhindra3000 requested changes

2022-01-06 09:36 UTC, Sudhindra3000 commented on lib/pages/company_page/components/overview.dart
> +      marketStatusTile(AppIcons().currentPrice, 'Current Price',
Make all the members of AppIcons class as static. Then we dont't have keep instantiating the class and just do `AppIcons.currentPrice`

2022-01-06 09:36 UTC, Sudhindra3000 commented on lib/pages/company_page/components/calculate_order_fee.dart
> +int calculateOrderFee(int totalPrice) {
This is not a widget or page right. We can have it under utils folder as `calculations.dart` or some other appropriate name. We can maintain all the common calculations in one file

2022-01-21 03:21 UTC, dhruv1294 requested changes

2022-01-21 03:21 UTC, dhruv1294 commented on lib/constants/icons.dart
> +  String balance = '/icon/balance.svg';
give full relatve path here to render in mobile like the old crosswihte and balance

2022-01-21 03:21 UTC, dhruv1294 commented on lib/constants/icons.dart
> +  String balance = '/icon/balance.svg';
'assets/icon/crosswhite.svg' for example

2022-01-21 03:21 UTC, dhruv1294 commented on lib/pages/company_page/components/trading_bottom_sheet.dart
> +void tradingBottomSheet(
break this widget into seperate methods?

2022-01-21 03:21 UTC, dhruv1294 commented on lib/navigation/route_generator.dart
> +                create: (context) => StockPricesBloc(),
is stockPricesBloc even used now in home page??

2022-01-21 03:21 UTC, dhruv1294 commented on lib/navigation/route_generator.dart
> +                create: (context) => StockPricesBloc(),
we can remove that bloc completely since we are using streambuilder for it ig

2022-01-21 09:30 UTC, satyamurti commented on lib/pages/company_page/components/overview.dart
> +      marketStatusTile(AppIcons().currentPrice, 'Current Price',
Done

2022-01-21 09:31 UTC, satyamurti commented on lib/pages/company_page/components/calculate_order_fee.dart
> +int calculateOrderFee(int totalPrice) {
moved it to calculations.dart

2022-01-21 09:31 UTC, satyamurti commented on lib/constants/icons.dart
> +  String balance = '/icon/balance.svg';
done

2022-01-21 10:23 UTC, satyamurti commented on lib/pages/company_page/components/trading_bottom_sheet.dart
> +void tradingBottomSheet(
done

2022-01-21 10:25 UTC, satyamurti commented on lib/navigation/route_generator.dart
> +                create: (context) => StockPricesBloc(),
removed StockPricesBloc completely

2022-01-21 16:02 UTC, dhruv1294 approved these changes

2022-01-22 06:19 UTC, merged