[Add] Stock bar
delta/dalal-street-client pull request #38
Opened 2021-12-28 19:06 UTC by siva2204

- add stock bar 

ps : check animation part (Marquee.dart)

2021-12-29 07:14 UTC, satyamurti requested changes

2021-12-29 07:14 UTC, satyamurti commented on lib/components/stock_bar.dart
> +                    ? Image.asset('assets/images/trendingUp.png',
Its better to use SVGs wherever possible because they are vector graphics which has very small file size, we can change colors, resize them without  losing image quality.

2021-12-29 18:37 UTC, satyamurti requested changes

2021-12-29 18:37 UTC, satyamurti commented on lib/components/stock_bar.dart
> +                        fontSize: 13,
change fontSize to 14

2021-12-29 18:37 UTC, satyamurti commented on lib/components/stock_bar.dart
> +                      color: whiteWithOpacity50,
`color : white`

2021-12-29 18:37 UTC, satyamurti commented on lib/components/stock_bar.dart
> +                Text('${oCcy.format(percentageHighOrLow).toString()}%',
Add rupee symbol `Text('₹' + oCcy.format(stockPrice).toString()`

2021-12-29 18:37 UTC, satyamurti commented on lib/components/stock_bar.dart
> +                  width: 3.0,
reduce this to 1

2021-12-29 18:39 UTC, satyamurti commented on lib/components/stock_bar.dart
> +            color: whiteWithOpacity75,
`color:white`

2021-12-29 18:39 UTC, satyamurti commented on lib/components/stock_bar.dart
> +          companyName,
make it uppercase according to figma mock up

2021-12-30 16:50 UTC, Sudhindra3000 requested changes

2021-12-30 16:50 UTC, Sudhindra3000 commented on lib/blocs/stock_bar/stockbar_cubit.dart
> +class StockbarCubit extends Cubit<StockbarState> {
We don't need this cubit. The `StockBar` widget only does one thing, listening to the prices stream. No real events are there either

We can simply use the `StreamBuilder` widget to rebuild the necessary sections of the ui. Just pass the prices stream as parameter. Watch this short [video](https://www.youtube.com/watch?v=MkKEWHfy99Y) to understand how it works

2022-01-06 09:29 UTC, siva2204 commented on lib/blocs/stock_bar/stockbar_cubit.dart
> +class StockbarCubit extends Cubit<StockbarState> {
`StreamBuilder` is great, but for the initial data i have to build data of type `StockUpdate`, which i feel is bit unnecessary.

2022-01-06 09:32 UTC, siva2204 commented
done with all the requested changes, pls to review @Sudhindra3000 @satyamurti

2022-01-06 18:43 UTC, siva2204 commented
![Screenshot from 2022-01-06 23-54-55](https://user-images.githubusercontent.com/63258524/148434064-23b47e13-42ec-4b87-b7a7-2dc6f8620416.png)

there is some inconsistency in data in company widget and stock bar ig, i think its because of usage of different data types(i used `int64` and `double`) @satyamurti

2022-01-07 05:51 UTC, Sudhindra3000 requested changes

2022-01-07 05:51 UTC, Sudhindra3000 commented on lib/constants/format.dart
> +final oCcy = NumberFormat('#,##0.00', 'en_US');
What does oCcy mean?
Can you give it a more meaningful name

2022-01-07 05:51 UTC, Sudhindra3000 commented on lib/components/stock_bar.dart
> +            stockId: i,
Rename `i` to `id` to avoid confusion

2022-01-07 05:51 UTC, Sudhindra3000 commented on lib/components/stock_bar.dart
> +  Stream<Int64> _getPerStockStreamMap(int stockId) {
- Rename the function to `priceStreamOfStock()`
- Separate this function from `StockBarMarquee` class
- Pass the stockMapStream as paramater. Don't make the function use `getIt` directly
- Call `.distinct()` at the end

2022-01-07 13:19 UTC, Sudhindra3000 approved these changes

2022-01-08 09:44 UTC, satyamurti approved these changes

2022-01-08 09:45 UTC, merged