[update]: update Exchange page UI to mockup
delta/dalal-street-client pull request #39
Opened 2022-01-01 10:12 UTC by dhruv1294

2022-01-01 15:07 UTC, Sudhindra3000 commented on lib/components/sheets/exchange_bottom_sheet.dart
> +    return BlocProvider(
Can you also split up this widget tree like in ExchangePage

2022-01-01 16:02 UTC, satyamurti requested changes

2022-01-01 16:02 UTC, satyamurti commented on lib/components/sheets/exchange_bottom_sheet.dart
> +                                          '/icon/balance.svg',
Create a file called `icons.dart` in `constants/` directory and add this string there, refer to trading_dashboard branch.

2022-01-02 06:26 UTC, dhruv1294 commented on lib/components/sheets/exchange_bottom_sheet.dart
> +                                          '/icon/balance.svg',
also need to find a fix for loading svg in mobile

2022-01-03 14:48 UTC, satyamurti commented on lib/components/sheets/exchange_bottom_sheet.dart
> +                                          '/icon/balance.svg',
we can have meet and resolve it

2022-01-05 07:21 UTC, Sudhindra3000 approved these changes

2022-01-05 17:14 UTC, satyamurti approved these changes

2022-01-06 04:01 UTC, merged