Feat: Added News page
delta/dalal-street-client pull request #46
Opened 2022-01-11 04:44 UTC by vpranavkrishna

2022-01-12 07:25 UTC, dhruv1294 requested changes

2022-01-12 07:25 UTC, dhruv1294 commented on lib/blocs/companies/companies_bloc.dart
> +          //  print(stockPrices);
remove commented print statements

2022-01-12 07:25 UTC, dhruv1294 commented on lib/blocs/market_events/market_event_event.dart
> +  final int lasteventid;
pls to follow camelcase

2022-01-13 06:25 UTC, Sudhindra3000 approved these changes

2022-01-13 08:40 UTC, dhruv1294 approved these changes

2022-01-13 09:08 UTC, Sudhindra3000 requested changes

2022-01-13 09:08 UTC, Sudhindra3000 commented on lib/navigation/route_generator.dart
> +      case '/news_page':
```suggestion
      case '/news':
```

2022-01-13 09:08 UTC, Sudhindra3000 commented on lib/blocs/market_events/market_event_event.dart
> +abstract class MarketEventEvents extends Equatable {
Rename this to `NewsEvent`
And rename the corresponding bloc and state classes to `NewsBloc` and `NewsState` as well

2022-01-13 10:43 UTC, Sudhindra3000 requested changes

2022-01-13 10:43 UTC, Sudhindra3000 commented on lib/blocs/market_events/market_event_state.dart
> +class SubscriptionToMarketEventFailed extends NewsState {
Rename these classes similarly

2022-01-13 10:44 UTC, Sudhindra3000 commented on lib/blocs/market_events/market_event_state.dart
> +class SubscriptionToMarketEventFailed extends NewsState {
And the names of the files and folders these bloc classes are in

2022-01-13 11:58 UTC, dhruv1294 commented
Also build is failing do fix it

2022-01-13 16:00 UTC, Sudhindra3000 approved these changes

2022-01-13 16:18 UTC, dhruv1294 approved these changes

2022-01-13 16:27 UTC, merged