[feat]: Add Mortgage page
delta/dalal-street-client pull request #50
Opened 2022-01-16 12:03 UTC by dhruv1294

2022-01-17 06:29 UTC, Sudhindra3000 requested changes

2022-01-17 06:29 UTC, Sudhindra3000 commented on lib/streams/transformations.dart
> +Stream<int> getStockOwnedMapStream(
```suggestion
Stream<int> getStocksOwnedStream(
```
As it is not returning a map but stocks owned in a single company

2022-01-17 06:29 UTC, Sudhindra3000 commented on lib/streams/transformations.dart
> +        .map((userInfo) => userInfo.stocksOwnedMap[stockId]!)
```suggestion
        .map((userInfo) => userInfo.stocksOwnedMap[stockId] ?? 0)
```

2022-01-19 06:53 UTC, Sudhindra3000 approved these changes

2022-01-20 08:44 UTC, satyamurti approved these changes

2022-01-20 08:44 UTC, merged