[feat]:Added News page UI
delta/dalal-street-client pull request #52
Opened 2022-01-18 11:23 UTC by vpranavkrishna

2022-01-21 11:15 UTC, satyamurti commented
![image](https://user-images.githubusercontent.com/59143264/150517735-d8da9c64-8ae7-4629-a2a6-e975f92f1ce7.png)
Looks like UI is still the same?

2022-01-21 11:17 UTC, satyamurti commented
Refer this UI 
![image](https://user-images.githubusercontent.com/59143264/150518098-931144a7-4358-4fbf-9692-77b3b14156ac.png)

2022-01-23 16:27 UTC, dhruv1294 approved these changes

2022-01-24 07:40 UTC, satyamurti requested changes
Can you send screen recording of the whole UI once ?

2022-01-29 08:28 UTC, siva2204 requested changes
we have append latest news form `marketevents stream` at first in the page

2022-01-29 08:28 UTC, siva2204 commented on lib/pages/news_page.dart
> +          context.read<NewsBloc>().add(GetMoreNews(mapMarketEvents.length + 1));
`lastEventId` stands for the latest narket event id thats not fetched yet

lets say we have 20 news in db, the first initial request will send 10 news of id [20,19,18..............12,11], to load the older news the `latestEventId` in this case will be `10` (11 - 1)

this has nothing to with the length, as long as `bool more_exists = 3;` is true in the response, we can fetch older news with the event id

ps : `event id`, `lastEventId` is the primary key in MarketEvents table

2022-01-29 08:28 UTC, siva2204 commented on lib/pages/news_page.dart
> +                  'Subscription To News Failed to load data \nReason : //',
can use `snackbar` for errors ?

2022-01-29 08:33 UTC, satyamurti commented on lib/pages/news_page.dart
> +                  'Subscription To News Failed to load data \nReason : //',
It will be shown in center of that section right. I think we should add retry button there.

2022-02-01 06:06 UTC, satyamurti commented
What is status of this PR?

2022-02-01 06:06 UTC, satyamurti commented
@vpranavkrishna

2022-02-02 09:34 UTC, satyamurti approved these changes
Can you send ss of UI

2022-02-02 17:46 UTC, merged