[WIP] Home page Graphs
delta/dalal-street-client pull request #54
Opened 2022-01-21 17:42 UTC by siva2204

2022-02-05 05:50 UTC, dhruv1294 approved these changes

2022-02-05 05:50 UTC, dhruv1294 commented
can remove commented code if not being used

2022-02-05 05:56 UTC, siva2204 commented
> can remove commented code if not being used

Will do with other changes

2022-02-07 16:46 UTC, Sudhindra3000 requested changes

2022-02-07 16:46 UTC, Sudhindra3000 commented on lib/blocs/stock_history/history/stock_history_state.dart
> +}
Override props field for both

2022-02-07 16:46 UTC, Sudhindra3000 commented on lib/components/graph/chart_enum.dart
> +enum ChartType { line, candlestick, bar }
Rename file to chart_type.dart

2022-02-07 16:46 UTC, Sudhindra3000 commented on lib/components/graph/stock_chart.dart
> +        .getStockHistoryUpdates(widget.stockId);
Subscribe to stream after initial data is fetched?

2022-02-07 16:55 UTC, siva2204 commented on lib/components/graph/stock_chart.dart
> +        .getStockHistoryUpdates(widget.stockId);
yes, in initial data of 60 `stockHistory` will be returned, the stream will have a single `stockHistory`, which will be added to the graph which is built from the data fetched initially.

2022-02-07 16:55 UTC, siva2204 commented on lib/components/graph/chart_enum.dart
> +enum ChartType { line, candlestick, bar }
okay sur :(

2022-02-09 05:20 UTC, Sudhindra3000 commented on lib/components/graph/stock_chart.dart
> +        .getStockHistoryUpdates(widget.stockId);
I meant wait till data is fetched and then subscribe to the stream

2022-02-09 06:18 UTC, siva2204 commented on lib/components/graph/stock_chart.dart
> +        .getStockHistoryUpdates(widget.stockId);
okay

2022-02-09 16:12 UTC, Sudhindra3000 approved these changes

2022-02-11 06:36 UTC, siva2204 commented
i'm going ahead to merge this pr, even though there is an [has](https://github.com/fluttercandies/flutter-interactive-chart/issues/14) issue with candle stick, which will not be a issue in real event(removing max price and min price resolves this)

2022-02-11 06:38 UTC, merged