[WIP] market depth
delta/dalal-street-client pull request #58
Opened 2022-01-23 13:12 UTC by siva2204

- add market depth

todo 
- ordering
- ui
- latest trades

2022-01-24 17:36 UTC, siva2204 commented
![Screenshot from 2022-01-24 23-03-46](https://user-images.githubusercontent.com/63258524/150834947-80a4be1e-338c-4cdd-9924-1cf54c0310b2.png)

2022-01-25 04:16 UTC, Sudhindra3000 requested changes

2022-01-25 04:16 UTC, Sudhindra3000 commented on lib/blocs/subscribe/subscribe_cubit.dart
> +      {String dataStreamId = '0'}) async {
```suggestion
      {String? dataStreamId}) async {
```

2022-01-26 07:09 UTC, Sudhindra3000 approved these changes

2022-01-26 07:31 UTC, merged