feat: admin dashboard
delta/dalal-street-client pull request #59
Opened 2022-01-24 16:11 UTC by subiksha2312

2022-01-25 04:43 UTC, 0149Sailesh commented
As discussed in the last meet, refactor your code by clubbing cubits that fall under the same category. 
Just have 4 cubit files. for eg: Stock specific, daily market specific, user specific, cheat specific.

2022-01-26 07:11 UTC, Sudhindra3000 requested changes

2022-01-26 07:11 UTC, Sudhindra3000 commented on lib/pages/admin_page/admin_page.dart
> +  BlocConsumer<Tab1Cubit, Tab1State> _onSendNews() {
Make the return type for all helper methods as `Widget`. So that you don't have to keep updating them when there's a change in the ui

2022-01-26 14:58 UTC, Sudhindra3000 requested changes

2022-01-26 14:58 UTC, Sudhindra3000 commented on lib/blocs/admin/tab1/tab1_state.dart
> +}
Instead of having loading, failure and success states for each rpc, have just one set. And give them tags to identify. It could be a string or an enum. Probably better to have an enum
Example:
```dart
enum AdminRpc{
  SendNews,
  SendNotif,
  .
  .
}

class RpcLoading extends StateClass {
  final AdminRpc tag;

  RpcLoading(this.tag);
}

Future<void> sendNews() async {
  emit(RpcLoading(AdminRpc.SendNews));
  // rpc call
  emit(RpcSuccess(AdminRpc.SendNews));
}
```

2022-01-26 15:01 UTC, Sudhindra3000 commented
And remove the unused cubit and state classes in blocs/admin folder

2022-01-28 16:22 UTC, dhruv1294 commented
also pull rebase once since there is a conflict

2022-01-28 17:08 UTC, Sudhindra3000 approved these changes

2022-01-28 17:20 UTC, dhruv1294 requested changes

2022-01-28 17:20 UTC, dhruv1294 commented on lib/main.dart
> -// TODO: do that thing where if we hit enter while filling a form the focus will shift to the next textfield, and submits the form on hitting enter in the last field. Don't know what it's called
are these todos done? if not then pls revert this change

2022-01-28 17:20 UTC, dhruv1294 commented on lib/pages/auth/register_page.dart
> -              // TODO: prefixIcon
this one as well

2022-01-28 17:20 UTC, dhruv1294 commented on lib/pages/auth/verify_phone/enter_otp_page.dart
> -    // TODO: form validation
same here

2022-01-28 17:20 UTC, dhruv1294 commented on lib/theme/theme.dart
> -// TODO: Fill colors are not showing properly
here as well

2022-01-28 18:09 UTC, merged