[feat]: Added Open orders page
delta/dalal-street-client pull request #66
Opened 2022-02-05 09:57 UTC by vpranavkrishna

2022-02-06 10:19 UTC, siva2204 commented
openOrder implementation looks good, one more thing we need add is real-time updates in open orders page

`GetMyOrderUpdates` server side rpc should be used for real-time updates

can be added with globalStreams similar to notfication stream.

with that you have to update/add open orders

2022-02-08 13:43 UTC, Sudhindra3000 requested changes

2022-02-08 13:43 UTC, Sudhindra3000 commented on lib/blocs/portfolio/open_orders/open_orders_cubit.dart
> +  Future<void> cancelOpenOrders(int? orderId, bool? isAsk) async {
```suggestion
  Future<void> cancelOpenOrder(int orderId, bool isAsk) async {
```

2022-02-08 13:43 UTC, Sudhindra3000 commented on lib/blocs/portfolio/open_orders/open_orders_cubit.dart
> +      final GetMyOpenOrdersResponse resp = await actionClient.getMyOpenOrders(
```suggestion
      final resp = await actionClient.getMyOpenOrders(
```
No need to specify type when declaring using `final` or `var`

2022-02-08 13:43 UTC, Sudhindra3000 commented on lib/blocs/portfolio/open_orders/open_orders_cubit.dart
> +      final GetMyOpenOrdersResponse resp = await actionClient.getMyOpenOrders(
Check this in other places too

2022-02-08 13:43 UTC, Sudhindra3000 commented on lib/blocs/portfolio/open_orders/open_orders_cubit.dart
> +      logger.i(e.toString());
```suggestion
      logger.e(e);
```
Log exceptions as errors everywhere

2022-02-08 13:43 UTC, Sudhindra3000 commented on lib/blocs/portfolio/open_orders/open_orders_state.dart
> +class OpenorderFailure extends OpenOrdersState {
Have just one state class `OrderFailure` for this and `CancelorderFailure`. And have a field to specify open or close order.
Could be an enum `OrderType` or a bool `isOpen`

2022-02-08 13:43 UTC, Sudhindra3000 commented on lib/blocs/portfolio/open_orders/open_orders_state.dart
> +class OpenordersSucess extends OpenOrdersState {
```suggestion
class GetOpenOrdersSuccess extends OpenOrdersState {
```

2022-02-08 13:43 UTC, Sudhindra3000 commented on lib/blocs/portfolio/open_orders/open_orders_state.dart
> +class CancelorderSucess extends OpenOrdersState {
```suggestion
class CancelOrderSucess extends OpenOrdersState {
```

2022-02-08 13:43 UTC, Sudhindra3000 commented on lib/blocs/portfolio/open_orders/open_orders_state.dart
> +class CancelorderSucess extends OpenOrdersState {
And typo in Success in some class names. Check that too

2022-02-08 13:52 UTC, Sudhindra3000 commented
Seems like you are using an image file for cancel button. There's already a `TertiaryButton` component. Use that instead

2022-02-08 14:06 UTC, Sudhindra3000 commented
> Looks like you are using an image file for cancel button. There's already a `TertiaryButton` component. Use that instead

Even if there wasn't a widget, you could just create one. Or just inline the required styles. It's not that hard. Don't use images or svg files for simple things like buttons

2022-02-08 14:09 UTC, Sudhindra3000 commented
> Few other things not related to open orders:
> 
> 1. Rename `NewsDetail` to `NewsDetailPage`, and the file to `news_detail_page.dart`
> 2. `NewsDetail` is accepting these as params:
>    ```dart
>     final String text;
>     final String imagePath;
>     final String headline;
>     final String dur;
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Just pass a `MarketEvent` object instead. It's the same thing
> 3. There's a field in NewsDetail widget called `String dur`. I'm guessing it's supposed to mean duration. Anyway that field will be removed after above change, but give better names to variables from now.
> 4. You are going from news page to news detail page by doing a manual `Navigator.push(NewsDetail(args))` everywhere. All individual pages must to be declared in `route_generator.dart`. And navigate to them using `Navigator.pushNamed` and pass in the route and required args

Better do these things in a separate pr, after open orders in done

2022-02-09 06:46 UTC, dhruv1294 requested changes

2022-02-09 06:46 UTC, dhruv1294 commented on lib/navigation/route_generator.dart
> +      case '/openorders':
pls name this according to sheet page routes, check dalal_home.dart, do the same for referAndEarn as well

2022-02-15 06:16 UTC, satyamurti requested changes
remove this image [dalal-street-client](https://github.com/delta/dalal-street-client/tree/openOrders)/[assets](https://github.com/delta/dalal-street-client/tree/openOrders/assets)/[images](https://github.com/delta/dalal-street-client/tree/openOrders/assets/images)/tertiary.png

instead use button widgets defined in `components/`

2022-02-16 16:41 UTC, Sudhindra3000 requested changes

2022-02-16 16:41 UTC, Sudhindra3000 commented on lib/pages/dalal_home/dalal_home.dart
> +            }),
Unnecessary changes will cause unnecessary merge conflicts for other working on the same file. Pls undo

2022-02-16 16:41 UTC, Sudhindra3000 commented on lib/blocs/open_orders_subscription/openorders_subscription_cubit.dart
> +import 'package:bloc/bloc.dart';
Rename file to `open_orders_sub....`. Do change in other places as well

2022-02-16 16:41 UTC, Sudhindra3000 commented on lib/pages/news/newsdetail_page.dart
> +import '../../theme/colors.dart';
Rename file to `news_detail_page.dart`. And match the filename with Class name

2022-02-16 17:05 UTC, Sudhindra3000 approved these changes

2022-02-16 17:53 UTC, kelpikz requested changes
- Make the open orders heading appBar
- Increase top margin for Open orders
- Change color of  Action, Detail, Status to blurred-gray and decrease its font size to mockup
- Make the actions row according to the mock up

- Fix all the overflows ( Make column to ListView or Use SingleChildScrollView )
- Pop up for canceling an order is not working

2022-02-17 04:46 UTC, dhruv1294 commented
Cancelling orders is working but it would be better if it cancelled order real-time.
So, when user long presses an item, try emitting the state again to make it look real-time

2022-02-17 04:48 UTC, dhruv1294 commented
Also, remove the tertiary.png since you are not using it currently.

2022-02-20 08:05 UTC, closed without merging