feat:added notifications page
delta/dalal-street-client pull request #74
Opened 2022-02-08 08:08 UTC by subiksha2312

2022-02-08 17:25 UTC, Sudhindra3000 requested changes

2022-02-08 17:25 UTC, Sudhindra3000 commented on lib/blocs/notifications/notifications_bloc.dart
> +class NotificationsBloc extends Bloc<NotificationsEvent, NotifState> {
This bloc seems pretty simple. Can convert to cubit

2022-02-08 17:25 UTC, Sudhindra3000 commented on lib/blocs/notifications/notifications_state.dart
> +  final GetNotificationsResponse notifList;
Rename to getNotifResponse

2022-02-08 17:25 UTC, Sudhindra3000 commented on lib/navigation/route_generator.dart
> +        );
Move this code block to below where home pages are handled. Easier to navigate

2022-02-08 17:25 UTC, Sudhindra3000 commented on lib/pages/notifications_page.dart
> +final notifStream = getIt<GlobalStreams>().notificationStream;
Declare this field inside `NotificationsPage`

2022-02-08 17:25 UTC, Sudhindra3000 commented on lib/pages/notifications_page.dart
> +  _onGetNotifications() {
Give a better name?
It's not really getting anything, but just showing the notifications

2022-02-08 17:25 UTC, Sudhindra3000 commented on lib/pages/notifications_page.dart
> +      }
You can override the `onChange` method in bloc. Do log statements during debugging there. It'll be easier to manage

2022-02-08 17:25 UTC, Sudhindra3000 commented on lib/pages/notifications_page.dart
> +        logger.i('unsuccessful');
Remove all kinds of log statements and functions calls in ui code. Only call functions in listeners

2022-02-08 17:25 UTC, Sudhindra3000 commented on lib/pages/notifications_page.dart
> +class NotifsDetail extends StatelessWidget {
Split this into a separate file

2022-02-11 16:47 UTC, Sudhindra3000 requested changes

2022-02-11 16:47 UTC, Sudhindra3000 commented on lib/blocs/notifications_cubit/notifications_cubit.dart
> +      emit(GetNotifFailure(e.toString()));
```suggestion
      emit(GetNotifFailure(failedToReachServer));
```
Always show this message in catch block. It's better to avoid showing grpc exceptions directly to user

2022-02-11 16:47 UTC, Sudhindra3000 commented on lib/blocs/notifications_cubit/notifications_cubit.dart
> +      emit(GetNotifFailure(e.toString()));
Do this everywhere

2022-02-11 18:33 UTC, Sudhindra3000 requested changes

2022-02-11 18:33 UTC, Sudhindra3000 commented on lib/blocs/notifications_cubit/notifications_cubit.dart
> +      emit(const GetNotifFailure(failedToReachServer));
Do this in other catch blocks in this cubit also

2022-02-11 18:33 UTC, Sudhindra3000 commented on lib/pages/notifications_page.dart
> +              return GestureDetector(
Remove `GestureDetector` if `onTap` is not used

2022-02-14 05:16 UTC, dhruv1294 commented on lib/pages/notifications_page.dart
> +                      return const SizedBox();
If this is the loading state, add progress bar instead of empty sizedbox

2022-02-14 05:16 UTC, dhruv1294 commented on lib/pages/notifications_page.dart
> +                // crossAxisAlignment: CrossAxisAlignment.start,
remove commented code

2022-02-14 12:54 UTC, Sudhindra3000 submitted a review, later dismissed

2022-02-14 16:43 UTC, satyamurti requested changes

2022-02-14 16:43 UTC, satyamurti commented on lib/pages/notifications_page.dart
> +                    child: Flexible(
Flexible should be directly used under Column or Row only, please update this

2022-02-15 05:48 UTC, siva2204 submitted a review, later dismissed
chuck the notification stream part, only fetch all the notifications alone

2022-02-15 05:48 UTC, siva2204 commented on lib/blocs/notifications_cubit/notifications_cubit.dart
> +  }
`getNotification` and `getMoreNotification` is basically the same
in `getNotification` the argument is `GetNotificationsRequest().lastNotificationId` defaults to zero

in server if that value is zero it send first set of data, can use single cubit

and change the directory name to `notification`

2022-02-15 05:48 UTC, siva2204 commented on lib/blocs/notifications_cubit/notifications_cubit.dart
> +  }
can remove this yeah?
its for debugging right ?

2022-02-15 05:48 UTC, siva2204 commented on assets/icon/notification-icon.svg
> +        </svg>
add new line

2022-02-15 05:48 UTC, siva2204 commented on lib/blocs/notifications_cubit/notifications_cubit.dart
> +      emit(GetNotifSuccess(notifResponse));
```suggestion
      if (notifResponse.statusCode == GetNotificationsResponse_StatusCode.OK){
        emit(GetNotifSuccess(notifResponse));
      }else {
        emit(GetNotifFailure(notifResponse.statusMessage));
      }
```

2022-02-15 05:48 UTC, siva2204 commented on lib/pages/notifications_page.dart
> +    as test;
why test, gib more meaning full name

2022-02-15 05:48 UTC, siva2204 commented on lib/pages/notifications_page.dart
> +  }
move this to utils

2022-02-15 05:48 UTC, siva2204 commented on lib/pages/notifications_page.dart
> +    if (!islatest) {
`isLatest` is `notification.broadcast` right
i dont understand this part

2022-02-15 06:06 UTC, satyamurti requested changes

2022-02-15 06:06 UTC, satyamurti commented on lib/pages/notifications_page.dart
> +            child: CircularProgressIndicator(
use `DalalLoadingBar` here

2022-02-15 06:06 UTC, satyamurti commented on lib/pages/notifications_page.dart
> +                      return const LinearProgressIndicator();
use `DalalLoadingBar` here too

2022-02-15 06:07 UTC, satyamurti commented
do `git pull origin master` and merge the changes

2022-02-18 17:15 UTC, dhruv1294 approved these changes

2022-02-19 17:27 UTC, Sudhindra3000 approved these changes

2022-02-19 17:33 UTC, merged