Feat(shimmer): create util shimmer widgets for different layouts
delta/dalal-street-client pull request #85
Opened 2022-02-17 15:48 UTC by kelpikz

created a bunch of re-useable shimmer widgets which can be used as visual indicators that data is being loaded for different layouts

2022-02-17 17:06 UTC, Sudhindra3000 requested changes

2022-02-17 17:06 UTC, Sudhindra3000 commented on lib/utils/shimmers.dart
> +/// A bunch of re-useable shimmer widgets for various use cases
Create a folder `lib/components/shimmer`, and keep each widget in a separate file

2022-02-17 17:06 UTC, Sudhindra3000 commented on lib/utils/shimmers.dart
> +                      )),
Add trailing commas everywhere. The widget tree will become easier to navigate

2022-02-17 17:07 UTC, Sudhindra3000 commented
And attach images for each widget

2022-02-18 11:55 UTC, Sudhindra3000 requested changes

2022-02-18 11:55 UTC, Sudhindra3000 commented on lib/components/shimmers/text_view.dart
> +class TextShimmer extends StatelessWidget {
Rename file to `text_shimmer.dart`. Make the class name match with file name. Do this everywhere

2022-02-18 11:55 UTC, Sudhindra3000 commented on lib/components/shimmers/text_view.dart
> +class TextShimmer extends StatelessWidget {
Can modify the TextShimmer to have only one shimmer thing instead of 3, and use it in list image and expanded image ones also?

2022-02-18 14:47 UTC, kelpikz commented on lib/components/shimmers/text_view.dart
> +class TextShimmer extends StatelessWidget {
I thought TextShimmer can be used in transactions or open orders which has 3 items in a row. maybe can have a parameter which can be passed to the widget which indicates the number of rows ?

2022-02-18 14:48 UTC, kelpikz commented on lib/components/shimmers/text_view.dart
> +class TextShimmer extends StatelessWidget {
And

> Can modify the TextShimmer to have only one shimmer thing instead of 3, and use it in list image and expanded image ones also?

I don't think its possible to use TextShimmer in list image and expanded image as they have different height and spacing

2022-02-20 07:32 UTC, Sudhindra3000 approved these changes

2022-02-21 08:30 UTC, merged