Desktop Leaderboard
delta/dalal-street-client pull request #89
Opened 2022-02-19 21:59 UTC by simmiggrwl

implemented web ui for leaderboard 
and fixed a minor bug in mobile implementation of the same

2022-02-21 06:46 UTC, siva2204 requested changes

2022-02-21 06:46 UTC, siva2204 commented on lib/pages/leaderboard_page/components/leaderboard_page_builder_web.dart
> +        .getLeaderboard(1, 10, widget.leaderboardType);
idt we need this, you're calling this again in lib/pages/leaderboard_page/components/leaderboard_table_web.dart

2022-02-21 06:46 UTC, siva2204 commented on lib/pages/leaderboard_page/leaderboard_page.dart
> +                            create: (context) => LeaderboardCubit(),
you are creating a cubit here, and creating again the same instance of cubit in the child level, i think creating any one of them will do.

same goes for all other 4 places also

2022-02-21 06:46 UTC, siva2204 commented on lib/pages/leaderboard_page/components/leaderboard_table_web.dart
> +    int y = 1;
meaningful naming are highly appreciated

2022-02-21 06:46 UTC, siva2204 commented on lib/pages/leaderboard_page/components/leaderboard_table_web.dart
> +                    );
this is code part is repeated twice, under `DailyLeaderboardSuccess` and `OverallLeaderboardSuccess`

can create a widget and pass leaderboardType as parameter ?

2022-02-21 06:46 UTC, siva2204 commented on lib/pages/leaderboard_page/components/leaderboard_table_web.dart
> +                  child: Image(image: AssetImage(imagePath)),
```suggestion
                  child: rank <= 3 ? Image(image: AssetImage(imagePath)) : null,
```

2022-02-21 06:46 UTC, siva2204 commented on lib/pages/leaderboard_page/components/leaderboard_table_web.dart
> +                  child: Image(image: AssetImage(imagePath)),
can remove this if else part with the above condition ig

2022-02-25 05:11 UTC, dhruv1294 commented on lib/pages/leaderboard_page/components/leaderboard_page_builder_web.dart
> +  }
remove this initstate if not using

2022-02-28 08:28 UTC, dhruv1294 approved these changes

2022-02-28 12:14 UTC, siva2204 approved these changes

2022-02-28 12:58 UTC, merged